# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d9d5df5f989adcdb57673830cb94b6e8e3939aebc7873ea63f33f5670d030e9372b64234d6ff006b80de1899e3d10e4813372c1d3be967b6a82738f1a2ae806

test:
  secret_key_base: d4c1b3b6a5364b96d423fd3c5a365dbb071da681d99df4c396aca6317b03b0ffb5e564b9db15bacbce051145ae8bb648488bf0eaef2b2d5d909ab0a9a90cf8c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
